SET IDENTITY_INSERT [dbo].[Student] ON
INSERT INTO [dbo].[Student] ([Id], [Name], [RollNo], [Password], [Degree], [Address], [Phone]) VALUES (1, N'Ayman Shafique                ', N'BSEF18M001                    ', N'Ayman1234                ', N'BSSE      ', N'Sanda Kalan, Lahore', N'09877871281')
INSERT INTO [dbo].[Student] ([Id], [Name], [RollNo], [Password], [Degree], [Address], [Phone]) VALUES (2, N'Fatima Asif                   ', N'BSEF18M002                    ', N'Fatima1234               ', N'SE        ', N'Riwaz Garden Near MAO, Lahore', N'03327871981')
INSERT INTO [dbo].[Student] ([Id], [Name], [RollNo], [Password], [Degree], [Address], [Phone]) VALUES (3, N'Naima Ilyas                   ', N'BSEF18M003                    ', N'Hello1234                ', N'BSSE      ', N'Defence Road, Lahore', N'02877873281')
INSERT INTO [dbo].[Student] ([Id], [Name], [RollNo], [Password], [Degree], [Address], [Phone]) VALUES (4, N'Wjeeha Amir                   ', N'BCSF18M001                    ', N'Hello1234                ', N'BSCS      ', N'Islampura, Lahore', N'03424471971')
INSERT INTO [dbo].[Student] ([Id], [Name], [RollNo], [Password], [Degree], [Address], [Phone]) VALUES (5, N'Aleena Ishfaq                 ', N'BCSF18M002                    ', N'Hello1234                ', N'BSCS      ', N'Joyshah, Lahore', N'03177883581')
INSERT INTO [dbo].[Student] ([Id], [Name], [RollNo], [Password], [Degree], [Address], [Phone]) VALUES (6, N'Saroash Wasi                  ', N'BITF18M001                    ', N'Hello1234                ', N'BSIT      ', N'Sanda Kalan Lahore', N'03575571976')
INSERT INTO [dbo].[Student] ([Id], [Name], [RollNo], [Password], [Degree], [Address], [Phone]) VALUES (7, N'Kinza Amir                    ', N'BITF18M002                    ', N'Hello1234                ', N'BSIT      ', N'Malik Munir Road Beri Peer, Lahore', N'03873441222')
INSERT INTO [dbo].[Student] ([Id], [Name], [RollNo], [Password], [Degree], [Address], [Phone]) VALUES (8, N'Sameen Shafique               ', N'BITF18M003                    ', N'Hello1234                ', N'BSIT      ', N'Muslim Pura, Lahore', N'03179331201')
INSERT INTO [dbo].[Student] ([Id], [Name], [RollNo], [Password], [Degree], [Address], [Phone]) VALUES (9, N'Zainab Asif                   ', N'BITF18M004                    ', N'Hello1234                ', N'BSIT      ', N'Chauburji, Lahore', N'03270971701')
INSERT INTO [dbo].[Student] ([Id], [Name], [RollNo], [Password], [Degree], [Address], [Phone]) VALUES (2003, N'Maryam Khalid                 ', N'BSIT0001                      ', N'Maryam1234               ', N'BSIT      ', N'Chauburji, Lahore', N'03288569771')
SET IDENTITY_INSERT [dbo].[Student] OFF
